[package]
name = "array-concat"
version = "0.0.0"
authors = ["inspier <devdevin541@gmail.com>"]
edition = "2018"
description = "Macros for concatenating const arrays at compile time."
license = "MIT"
readme = "README.md"
